[package]
name = "ac-library-rs"
version = "0.1.0"
authors = ["rust-lang-ja Developers"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rand = "0.7.3"
