[package]
name = "ac-library-rs"
version = "0.1.0"
authors = ["matsu7874 <mtsmtkmt@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
proconio = "=0.3.6"
rand = "0.7.3"
